// Code generated by "stringer -output=stringer.Type.go -type=Type"; DO NOT EDIT.

package money

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Fiat-1]
	_ = x[Crypto-2]
}

const _Type_name = "FiatCrypto"

var _Type_index = [...]uint8{0, 4, 10}

func (i Type) String() string {
	i -= 1
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
